export const START = "START";
export const DISPLAY_ADD_ACCOUNT_ACTION = "DISPLAY_ADD_ACCOUNT_ACTION";
export const DISPLAY_ACCOUNTS_ACTION = "DISPLAY_ACCOUNTS_ACTION";
export const ADD_NEW_ACCOUNTS_ACTION = "ADD_NEW_ACCOUNTS_ACTION";
export const DELETE_ACCOUNT_ACTION = "DELETE_ACCOUNT_ACTION";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
