export const START = "START";
export const DISPLAY_ADD_ACCOUNT_ACTION = "DISPLAY_ADD_ACCOUNT_ACTION";
export const DISPLAY_ACCOUNTS_ACTION = "DISPLAY_ACCOUNTS_ACTION";
export const ADD_NEW_ACCOUNTS_ACTION = "ADD_NEW_ACCOUNTS_ACTION";